"use client";

import { IconWrapper } from "@/components/ui/icon-wrapper";
import {
  ChevronLeft,
  Globe,
  MapPin,
  Phone,
  Mail,
  ExternalLink,
  Play,
  Sparkles,
  Send,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Zap,
  TrendingUp,
  Clock,
  Eye,
  User,
  Building2,
  ArrowRight,
  Activity,
  LayoutTemplate,
  ShieldCheck,
  Ban,
  RotateCcw,
  FileText,
  History,
  Target,
  CircleCheckBig,
  CircleX,
  LogOut,
} from "lucide-react";

// Exportiere alle Icons als IconWrapper-Versionen
export const Icons = {
  ChevronLeft: (props: { className?: string }) => <IconWrapper icon={ChevronLeft} {...props} />,
  Globe: (props: { className?: string }) => <IconWrapper icon={Globe} {...props} />,
  MapPin: (props: { className?: string }) => <IconWrapper icon={MapPin} {...props} />,
  Phone: (props: { className?: string }) => <IconWrapper icon={Phone} {...props} />,
  Mail: (props: { className?: string }) => <IconWrapper icon={Mail} {...props} />,
  ExternalLink: (props: { className?: string }) => <IconWrapper icon={ExternalLink} {...props} />,
  Play: (props: { className?: string }) => <IconWrapper icon={Play} {...props} />,
  Sparkles: (props: { className?: string }) => <IconWrapper icon={Sparkles} {...props} />,
  Send: (props: { className?: string }) => <IconWrapper icon={Send} {...props} />,
  CheckCircle: (props: { className?: string }) => <IconWrapper icon={CheckCircle} {...props} />,
  XCircle: (props: { className?: string }) => <IconWrapper icon={XCircle} {...props} />,
  AlertTriangle: (props: { className?: string }) => <IconWrapper icon={AlertTriangle} {...props} />,
  Zap: (props: { className?: string }) => <IconWrapper icon={Zap} {...props} />,
  TrendingUp: (props: { className?: string }) => <IconWrapper icon={TrendingUp} {...props} />,
  Clock: (props: { className?: string }) => <IconWrapper icon={Clock} {...props} />,
  Eye: (props: { className?: string }) => <IconWrapper icon={Eye} {...props} />,
  User: (props: { className?: string }) => <IconWrapper icon={User} {...props} />,
  Building2: (props: { className?: string }) => <IconWrapper icon={Building2} {...props} />,
  ArrowRight: (props: { className?: string }) => <IconWrapper icon={ArrowRight} {...props} />,
  Activity: (props: { className?: string }) => <IconWrapper icon={Activity} {...props} />,
  LayoutTemplate: (props: { className?: string }) => <IconWrapper icon={LayoutTemplate} {...props} />,
  ShieldCheck: (props: { className?: string }) => <IconWrapper icon={ShieldCheck} {...props} />,
  Ban: (props: { className?: string }) => <IconWrapper icon={Ban} {...props} />,
  RotateCcw: (props: { className?: string }) => <IconWrapper icon={RotateCcw} {...props} />,
  FileText: (props: { className?: string }) => <IconWrapper icon={FileText} {...props} />,
  History: (props: { className?: string }) => <IconWrapper icon={History} {...props} />,
  Target: (props: { className?: string }) => <IconWrapper icon={Target} {...props} />,
  CircleCheckBig: (props: { className?: string }) => <IconWrapper icon={CircleCheckBig} {...props} />,
  CircleX: (props: { className?: string }) => <IconWrapper icon={CircleX} {...props} />,
  LogOut: (props: { className?: string }) => <IconWrapper icon={LogOut} {...props} />,
};
